[package]
name = "nadouf-math"
version = "0.1.2"
edition = "2024"
authors = ["Nadouvvv <nadoufmail@gmail.com>"]
description = "fast and safety python library"
license = "MIT"
repository = "https://github.com/CrabNadouf/Nadouf_Math_Library"
readme = "README.md"

[lib]
name = "nadouf_math"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module", "num-bigint"] }
num-bigint = "0.4"
num-traits = "0.2"
